server {
listen 80;
server_name localhost;
root  /usr/share/nginx/html;
index index.html;

location / {

  try_files $uri $uri/ /index.html;
}
error_page 404 /index.html;
}
  #try_files $uri существует ли файл по этому пути
# $uri/  может быть это директория , тогда отдавай содержимое директории
#/index.html если ни того,ни другого нет, отдай index.html там уже раутинг прописан